export const LOGGER_MICROSERVICE = 'LOGGER_MICROSERVICE';
export const USER_MICROSERVICE = 'USER_MICROSERVICE';
export const AUTH_MICROSERVICE = 'AUTH_MICROSERVICE';
export const FINANCE_MICROSERVICE = 'FINANCE_MICROSERVICE';
